"""add_created_by_to_pets

Revision ID: 4853a5452c14
Revises: 1c81a230458f
Create Date: 2025-11-07 00:47:21.013855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4853a5452c14'
down_revision: Union[str, Sequence[str], None] = '1c81a230458f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop files table and indexes if they exist
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'files' in inspector.get_table_names():
        # Drop foreign keys first
        fks = inspector.get_foreign_keys('files')
        for fk in fks:
            op.drop_constraint(fk['name'], 'files', type_='foreignkey')
        
        # Drop indexes
        indexes = inspector.get_indexes('files')
        index_names = [idx['name'] for idx in indexes]
        
        for index_name in index_names:
            try:
                op.drop_index(index_name, table_name='files')
            except:
                pass  # Index might already be dropped or not exist
        
        # Drop the table
        op.drop_table('files')
    
    op.add_column('adoption_applications', sa.Column('application_id', sa.String(length=20), nullable=False))
    op.add_column('adoption_applications', sa.Column('personal_info', sa.JSON(), nullable=False))


    op.add_column('adoption_applications', sa.Column('living_environment', sa.JSON(), nullable=False))
    op.add_column('adoption_applications', sa.Column('pet_experience', sa.JSON(), nullable=False))
    op.add_column('adoption_applications', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('adoption_applications', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('adoption_applications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('adoption_applications', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_adoption_applications_applicant_id'), 'adoption_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_adoption_applications_application_id'), 'adoption_applications', ['application_id'], unique=True)
    op.create_index(op.f('ix_adoption_applications_pet_id'), 'adoption_applications', ['pet_id'], unique=False)
    op.create_index(op.f('ix_adoption_applications_status'), 'adoption_applications', ['status'], unique=False)
    op.drop_column('adoption_applications', 'application_data')
    op.drop_column('adoption_applications', 'notes')
    op.add_column('chat_rooms', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('chat_rooms', sa.Column('type', sa.Enum('ADOPTION', 'SUPPORT', 'GENERAL', name='chatroomtype'), nullable=False))
    op.add_column('chat_rooms', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.alter_column('chat_rooms', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('chat_rooms', 'application_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('chat_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('uq_chat_rooms_application_id'), table_name='chat_rooms')
    op.create_index(op.f('ix_chat_rooms_application_id'), 'chat_rooms', ['application_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_pet_id'), 'chat_rooms', ['pet_id'], unique=False)
    op.create_foreign_key(op.f('fk_chat_rooms_pet_id_pets'), 'chat_rooms', 'pets', ['pet_id'], ['id'])
    op.drop_column('chat_rooms', 'updated_at')
    op.add_column('messages', sa.Column('room_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('messages', 'file_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.drop_constraint(op.f('fk_messages_chat_room_id_chat_rooms'), 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_room_id_chat_rooms'), 'messages', 'chat_rooms', ['room_id'], ['id'])
    op.drop_column('messages', 'chat_room_id')
    op.drop_column('messages', 'is_read')
    op.add_column('notifications', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('related_id', sa.Integer(), nullable=True))
    op.alter_column('notifications', 'type',
               existing_type=mysql.ENUM('application', 'message', 'system', 'reminder', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('APPLICATION_STATUS', 'MESSAGE', 'SYSTEM', 'REMINDER', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'metadata')
    op.drop_column('notifications', 'updated_at')
    op.create_index(op.f('ix_pet_history_id'), 'pet_history', ['id'], unique=False)
    op.drop_constraint(op.f('fk_pet_history_pet_id_pets'), 'pet_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_pet_history_changed_by_users'), 'pet_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pet_history_pet_id_pets'), 'pet_history', 'pets', ['pet_id'], ['id'])
    op.create_foreign_key(op.f('fk_pet_history_changed_by_users'), 'pet_history', 'users', ['changed_by'], ['id'])
    op.add_column('pets', sa.Column('health_status', sa.Text(), nullable=True))
    op.add_column('pets', sa.Column('sterilized', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('pets', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('pets', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('pets', sa.Column('last_modified_by', sa.Integer(), nullable=True))
    op.alter_column('pets', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('pets', 'size',
               existing_type=mysql.ENUM('small', 'medium', 'large', 'extra_large', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('pets', 'vaccination_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('pets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('pets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_pets_breed'), 'pets', ['breed'], unique=False)
    op.create_index(op.f('ix_pets_created_by'), 'pets', ['created_by'], unique=False)
    op.create_index(op.f('ix_pets_gender'), 'pets', ['gender'], unique=False)
    op.create_index(op.f('ix_pets_location'), 'pets', ['location'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    op.create_index(op.f('ix_pets_shelter_id'), 'pets', ['shelter_id'], unique=False)
    op.create_index(op.f('ix_pets_size'), 'pets', ['size'], unique=False)
    op.create_foreign_key(op.f('fk_pets_created_by_users'), 'pets', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_pets_last_modified_by_users'), 'pets', 'users', ['last_modified_by'], ['id'])
    op.drop_column('pets', 'house_trained')
    op.drop_column('pets', 'spayed_neutered')
    op.drop_column('pets', 'age_years')
    op.drop_column('pets', 'medical_info')
    op.drop_column('pets', 'videos')
    op.drop_column('pets', 'energy_level')
    op.drop_column('pets', 'photos')
    op.drop_column('pets', 'behavioral_info')
    op.drop_column('pets', 'weight_kg')
    op.drop_column('pets', 'good_with_kids')
    op.drop_column('pets', 'documents')
    op.drop_column('pets', 'microchip_id')
    op.drop_column('pets', 'good_with_pets')
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.add_column('pets', sa.Column('good_with_pets', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('microchip_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('pets', sa.Column('documents', mysql.JSON(), nullable=True))
    op.add_column('pets', sa.Column('good_with_kids', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('weight_kg', mysql.FLOAT(), nullable=True))
    op.add_column('pets', sa.Column('behavioral_info', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('pets', sa.Column('photos', mysql.JSON(), nullable=True))
    op.add_column('pets', sa.Column('energy_level', mysql.ENUM('low', 'medium', 'high', collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('pets', sa.Column('videos', mysql.JSON(), nullable=True))
    op.add_column('pets', sa.Column('medical_info', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('pets', sa.Column('age_years', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('spayed_neutered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('house_trained', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_pets_last_modified_by_users'), 'pets', type_='foreignkey')
    op.drop_constraint(op.f('fk_pets_created_by_users'), 'pets', type_='foreignkey')
    op.drop_index(op.f('ix_pets_size'), table_name='pets')
    op.drop_index(op.f('ix_pets_shelter_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index(op.f('ix_pets_location'), table_name='pets')
    op.drop_index(op.f('ix_pets_gender'), table_name='pets')
    op.drop_index(op.f('ix_pets_created_by'), table_name='pets')
    op.drop_index(op.f('ix_pets_breed'), table_name='pets')
    op.alter_column('pets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pets', 'vaccination_status',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('pets', 'size',
               existing_type=mysql.ENUM('small', 'medium', 'large', 'extra_large', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('pets', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_column('pets', 'last_modified_by')
    op.drop_column('pets', 'version')
    op.drop_column('pets', 'created_by')
    op.drop_column('pets', 'location')
    op.drop_column('pets', 'sterilized')
    op.drop_column('pets', 'health_status')
    op.drop_constraint(op.f('fk_pet_history_changed_by_users'), 'pet_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_pet_history_pet_id_pets'), 'pet_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pet_history_changed_by_users'), 'pet_history', 'users', ['changed_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_pet_history_pet_id_pets'), 'pet_history', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pet_history_id'), table_name='pet_history')
    op.add_column('notifications', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('notifications', sa.Column('metadata', mysql.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('notifications', sa.Column('action_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('APPLICATION_STATUS', 'MESSAGE', 'SYSTEM', 'REMINDER', name='notificationtype'),
               type_=mysql.ENUM('application', 'message', 'system', 'reminder', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('notifications', 'related_id')
    op.drop_column('notifications', 'content')
    op.add_column('messages', sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('chat_room_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_messages_room_id_chat_rooms'), 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_chat_room_id_chat_rooms'), 'messages', 'chat_rooms', ['chat_room_id'], ['id'])
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('messages', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('messages', 'file_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'file_size')
    op.drop_column('messages', 'file_name')
    op.drop_column('messages', 'room_id')
    op.add_column('chat_rooms', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(op.f('fk_chat_rooms_pet_id_pets'), 'chat_rooms', type_='foreignkey')
    op.drop_index(op.f('ix_chat_rooms_pet_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_application_id'), table_name='chat_rooms')
    op.create_index(op.f('uq_chat_rooms_application_id'), 'chat_rooms', ['application_id'], unique=True)
    op.alter_column('chat_rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('chat_rooms', 'application_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('chat_rooms', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('chat_rooms', 'pet_id')
    op.drop_column('chat_rooms', 'type')
    op.drop_column('chat_rooms', 'name')
    op.add_column('adoption_applications', sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('adoption_applications', sa.Column('application_data', mysql.JSON(), nullable=True))
    op.drop_index(op.f('ix_adoption_applications_status'), table_name='adoption_applications')
    op.drop_index(op.f('ix_adoption_applications_pet_id'), table_name='adoption_applications')
    op.drop_index(op.f('ix_adoption_applications_application_id'), table_name='adoption_applications')
    op.drop_index(op.f('ix_adoption_applications_applicant_id'), table_name='adoption_applications')
    op.alter_column('adoption_applications', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('adoption_applications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('adoption_applications', 'submitted_at')
    op.drop_column('adoption_applications', 'review_notes')
    op.drop_column('adoption_applications', 'pet_experience')
    op.drop_column('adoption_applications', 'living_environment')
    op.drop_column('adoption_applications', 'personal_info')
    op.drop_column('adoption_applications', 'application_id')
    op.create_table('files',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='存儲的檔案名稱'),
    sa.Column('original_filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='原始檔案名稱'),
    sa.Column('file_size', mysql.BIGINT(), autoincrement=False, nullable=False, comment='檔案大小 (bytes)'),
    sa.Column('mime_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='MIME 類型'),
    sa.Column('file_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False, comment='SHA-256 hash'),
    sa.Column('storage_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='S3 儲存路徑'),
    sa.Column('category', mysql.ENUM('pet_photo', 'document', 'avatar'), nullable=False, comment='檔案類別'),
    sa.Column('related_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='關聯 ID (pet_id, user_id 等)'),
    sa.Column('uploaded_by', mysql.INTEGER(), autoincrement=False, nullable=False, comment='上傳者 user_id'),
    sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否公開'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='軟刪除標記'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='創建時間'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='刪除時間'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_files_uploaded_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='檔案儲存記錄表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='檔案儲存記錄表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_files_is_deleted'), 'files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_files_file_hash'), 'files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_files_category_related'), 'files', ['category', 'related_id'], unique=False)
    # ### end Alembic commands ###
