"""merge_first_last_name_to_name

Revision ID: 623743c6733f
Revises: e7ca5268b4cb
Create Date: 2025-11-08 18:07:23.224659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '623743c6733f'
down_revision: Union[str, Sequence[str], None] = 'e7ca5268b4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_comments_author_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_pet_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_post_type'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_post_likes_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_user_id'), table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index(op.f('uq_chat_rooms_application_id'), table_name='chat_rooms')
    op.create_index(op.f('ix_chat_rooms_application_id'), 'chat_rooms', ['application_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_pet_id'), 'chat_rooms', ['pet_id'], unique=False)
    op.create_foreign_key(op.f('fk_chat_rooms_pet_id_pets'), 'chat_rooms', 'pets', ['pet_id'], ['id'])
    op.drop_column('chat_rooms', 'updated_at')
    op.drop_index(op.f('date'), table_name='daily_metrics')
    op.drop_index(op.f('idx_date'), table_name='daily_metrics')
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=True)
    op.create_index(op.f('ix_daily_metrics_id'), 'daily_metrics', ['id'], unique=False)
    op.alter_column('inquiries', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('pending', 'in_progress', 'resolved', 'closed', name='inquirystatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('inquiries', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inquiries', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_pet_id'), table_name='inquiries')
    op.drop_index(op.f('idx_user_id'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_id'), 'inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_inquiries_pet_id'), 'inquiries', ['pet_id'], unique=False)
    op.create_index(op.f('ix_inquiries_shelter_id'), 'inquiries', ['shelter_id'], unique=False)
    op.create_index(op.f('ix_inquiries_user_id'), 'inquiries', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_inquiries_user_id_users'), 'inquiries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_inquiries_responded_by_users'), 'inquiries', 'users', ['responded_by'], ['id'])
    op.create_foreign_key(op.f('fk_inquiries_pet_id_pets'), 'inquiries', 'pets', ['pet_id'], ['id'])
    op.add_column('messages', sa.Column('room_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('messages', 'file_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.drop_constraint(op.f('fk_messages_chat_room_id_chat_rooms'), 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_room_id_chat_rooms'), 'messages', 'chat_rooms', ['room_id'], ['id'])
    op.drop_column('messages', 'chat_room_id')
    op.drop_column('messages', 'is_read')
    op.add_column('notifications', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('related_id', sa.Integer(), nullable=True))
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_column('notifications', 'metadata')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'updated_at')
    op.create_index(op.f('ix_pet_history_id'), 'pet_history', ['id'], unique=False)
    op.drop_constraint(op.f('fk_pet_history_pet_id_pets'), 'pet_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_pet_history_changed_by_users'), 'pet_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pet_history_changed_by_users'), 'pet_history', 'users', ['changed_by'], ['id'])
    op.create_foreign_key(op.f('fk_pet_history_pet_id_pets'), 'pet_history', 'pets', ['pet_id'], ['id'])
    op.create_index(op.f('ix_pet_statistics_id'), 'pet_statistics', ['id'], unique=False)
    op.alter_column('pets', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('pets', 'size',
               existing_type=mysql.ENUM('small', 'medium', 'large', 'extra_large', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('pets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('pets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_pets_last_modified_by'), table_name='pets')
    op.create_index(op.f('ix_pets_breed'), 'pets', ['breed'], unique=False)
    op.create_index(op.f('ix_pets_gender'), 'pets', ['gender'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    op.create_index(op.f('ix_pets_shelter_id'), 'pets', ['shelter_id'], unique=False)
    op.create_index(op.f('ix_pets_size'), 'pets', ['size'], unique=False)
    op.alter_column('review_decisions', 'review_completed',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('review_decisions', 'is_final',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_review_decisions_id'), 'review_decisions', ['id'], unique=False)
    op.drop_index(op.f('idx_session_id'), table_name='user_behaviors')
    op.create_index(op.f('ix_user_behaviors_id'), 'user_behaviors', ['id'], unique=False)
    op.create_index(op.f('ix_user_behaviors_session_id'), 'user_behaviors', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_behaviors_timestamp'), 'user_behaviors', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=200), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.alter_column('vaccinations', 'vaccine_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('CORE', 'NON_CORE', 'OPTIONAL', name='vaccinetype'),
               existing_nullable=False,
               existing_server_default=sa.text("'core'"))
    op.alter_column('vaccinations', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('COMPLETED', 'SCHEDULED', 'OVERDUE', 'CANCELLED', name='vaccinationstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'"))
    op.alter_column('vaccinations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vaccinations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_pet_id'), table_name='vaccinations')
    op.drop_index(op.f('idx_status'), table_name='vaccinations')
    op.create_index(op.f('ix_vaccinations_id'), 'vaccinations', ['id'], unique=False)
    op.create_index(op.f('ix_vaccinations_pet_id'), 'vaccinations', ['pet_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_status'), 'vaccinations', ['status'], unique=False)
    op.drop_constraint(op.f('vaccinations_ibfk_1'), 'vaccinations', type_='foreignkey')
    op.drop_constraint(op.f('vaccinations_ibfk_2'), 'vaccinations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vaccinations_pet_id_pets'), 'vaccinations', 'pets', ['pet_id'], ['id'])
    op.create_foreign_key(op.f('fk_vaccinations_administered_by_users'), 'vaccinations', 'users', ['administered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vaccinations_administered_by_users'), 'vaccinations', type_='foreignkey')
    op.drop_constraint(op.f('fk_vaccinations_pet_id_pets'), 'vaccinations', type_='foreignkey')
    op.create_foreign_key(op.f('vaccinations_ibfk_2'), 'vaccinations', 'users', ['administered_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('vaccinations_ibfk_1'), 'vaccinations', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vaccinations_status'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_pet_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_id'), table_name='vaccinations')
    op.create_index(op.f('idx_status'), 'vaccinations', ['status'], unique=False)
    op.create_index(op.f('idx_pet_id'), 'vaccinations', ['pet_id'], unique=False)
    op.alter_column('vaccinations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('vaccinations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vaccinations', 'status',
               existing_type=sa.Enum('COMPLETED', 'SCHEDULED', 'OVERDUE', 'CANCELLED', name='vaccinationstatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'"))
    op.alter_column('vaccinations', 'vaccine_type',
               existing_type=sa.Enum('CORE', 'NON_CORE', 'OPTIONAL', name='vaccinetype'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'core'"))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_user_behaviors_timestamp'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_session_id'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_id'), table_name='user_behaviors')
    op.create_index(op.f('idx_session_id'), 'user_behaviors', ['session_id'], unique=False)
    op.drop_index(op.f('ix_review_decisions_id'), table_name='review_decisions')
    op.alter_column('review_decisions', 'is_final',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('review_decisions', 'review_completed',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_pets_size'), table_name='pets')
    op.drop_index(op.f('ix_pets_shelter_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index(op.f('ix_pets_gender'), table_name='pets')
    op.drop_index(op.f('ix_pets_breed'), table_name='pets')
    op.create_index(op.f('ix_pets_last_modified_by'), 'pets', ['last_modified_by'], unique=False)
    op.alter_column('pets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pets', 'size',
               existing_type=mysql.ENUM('small', 'medium', 'large', 'extra_large', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('pets', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_index(op.f('ix_pet_statistics_id'), table_name='pet_statistics')
    op.drop_constraint(op.f('fk_pet_history_pet_id_pets'), 'pet_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_pet_history_changed_by_users'), 'pet_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pet_history_changed_by_users'), 'pet_history', 'users', ['changed_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_pet_history_pet_id_pets'), 'pet_history', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pet_history_id'), table_name='pet_history')
    op.add_column('notifications', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('notifications', sa.Column('action_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('notifications', sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('notifications', sa.Column('metadata', mysql.JSON(), nullable=True))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('notifications', 'related_id')
    op.drop_column('notifications', 'content')
    op.add_column('messages', sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('chat_room_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_messages_room_id_chat_rooms'), 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_chat_room_id_chat_rooms'), 'messages', 'chat_rooms', ['chat_room_id'], ['id'])
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('messages', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('messages', 'file_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'file_size')
    op.drop_column('messages', 'file_name')
    op.drop_column('messages', 'room_id')
    op.drop_constraint(op.f('fk_inquiries_pet_id_pets'), 'inquiries', type_='foreignkey')
    op.drop_constraint(op.f('fk_inquiries_responded_by_users'), 'inquiries', type_='foreignkey')
    op.drop_constraint(op.f('fk_inquiries_user_id_users'), 'inquiries', type_='foreignkey')
    op.drop_index(op.f('ix_inquiries_user_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_shelter_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_pet_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_id'), table_name='inquiries')
    op.create_index(op.f('idx_user_id'), 'inquiries', ['user_id'], unique=False)
    op.create_index(op.f('idx_pet_id'), 'inquiries', ['pet_id'], unique=False)
    op.alter_column('inquiries', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('inquiries', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inquiries', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'resolved', 'closed', name='inquirystatus'),
               type_=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.drop_index(op.f('ix_daily_metrics_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.create_index(op.f('idx_date'), 'daily_metrics', ['date'], unique=False)
    op.create_index(op.f('date'), 'daily_metrics', ['date'], unique=True)
    op.add_column('chat_rooms', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(op.f('fk_chat_rooms_pet_id_pets'), 'chat_rooms', type_='foreignkey')
    op.drop_index(op.f('ix_chat_rooms_pet_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_application_id'), table_name='chat_rooms')
    op.create_index(op.f('uq_chat_rooms_application_id'), 'chat_rooms', ['application_id'], unique=True)
    op.create_table('post_likes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('fk_post_likes_post_id_community_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_post_likes_user_id'), 'post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_likes_id'), 'post_likes', ['id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('post_type', mysql.ENUM('testimonial', 'discussion'), nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('is_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_featured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('likes_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_community_posts_author_id_users'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='fk_community_posts_pet_id_pets'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_community_posts_post_type'), 'community_posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_community_posts_pet_id'), 'community_posts', ['pet_id'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_post_comments_author_id_users')),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('fk_post_comments_post_id_community_posts')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comments_id'), 'post_comments', ['id'], unique=False)
    op.create_index(op.f('ix_post_comments_author_id'), 'post_comments', ['author_id'], unique=False)
    # ### end Alembic commands ###
